# Generated by Django 3.2.7 on 2021-09-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('READING', 'Reading'), ('REVISION', 'Revision'), ('WRITING', 'Writing')], default='READING', max_length=15),
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
