# Generated by Django 3.2.7 on 2021-12-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_auto_20211215_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attend',
            field=models.BooleanField(default=False),
        ),
    ]
