# Generated by Django 3.2.7 on 2021-12-16 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_alter_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='sid',
        ),
    ]
